engines:
  rubocop:
    enabled: false
  brakeman:
    enabled: false
  eslint:
    enabled: false
  csslint:
    enabled: false
  fixme:
    enabled: true
    config:
      strings:
        - CUSTOM
        - FIXME
        - HACK
        - TODO
        - BUG
  tslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - javascript
ratings:
  paths:
    - src/**
exclude_paths:
  - "*.js"
  - "*.md"
  - ".codeclimate.yml"
  - ".travis.yml"
  - "index.html"
  - "*.json"
  - "dist/**"
  - "spec/**/*"
  - "web-src/**/*"
  - "coverage/**/*"
  - "node_modules/**/*"